<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0l9zLi6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0l9zLi6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0l9zLi6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0l9zLi6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

<<<<<<< HEAD
return new \ContainerBjZBHno\App_KernelDevDebugContainer([
    'container.build_hash' => 'BjZBHno',
    'container.build_id' => '324e530f',
    'container.build_time' => 1764327508,
=======
return new \Container0l9zLi6\App_KernelDevDebugContainer([
    'container.build_hash' => '0l9zLi6',
    'container.build_id' => 'd07ef731',
    'container.build_time' => 1764061136,
>>>>>>> aa5eb33b3329458be52878198861bb1a6edf7915
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0l9zLi6');
