<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'getAllMenus' => [[], ['_controller' => 'App\\Menus\\MenusController\\MenuController::FindAll'], [], [['text', '/Menus']], [], [], []],
    'getMenuById' => [['id'], ['_controller' => 'App\\Menus\\MenusController\\MenuController::FindById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Menus']], [], [], []],
    'createMenu' => [[], ['_controller' => 'App\\Menus\\MenusController\\MenuController::Create'], [], [['text', '/Menus']], [], [], []],
    'updateMenu' => [['id'], ['_controller' => 'App\\Menus\\MenusController\\MenuController::Update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Menus']], [], [], []],
    'deleteMenu' => [['id'], ['_controller' => 'App\\Menus\\MenusController\\MenuController::Delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Menus']], [], [], []],
    'getAllProducts' => [[], ['_controller' => 'App\\Products\\ProductsController\\ProductsController::FindAll'], [], [['text', '/Products']], [], [], []],
    'getProductById' => [['id'], ['_controller' => 'App\\Products\\ProductsController\\ProductsController::FindById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Products']], [], [], []],
    'createProduct' => [[], ['_controller' => 'App\\Products\\ProductsController\\ProductsController::Create'], [], [['text', '/Products']], [], [], []],
    'updateProduct' => [['id'], ['_controller' => 'App\\Products\\ProductsController\\ProductsController::Update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Products']], [], [], []],
    'deleteProduct' => [['id'], ['_controller' => 'App\\Products\\ProductsController\\ProductsController::Delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Products']], [], [], []],
    'getAllReservations' => [[], ['_controller' => 'App\\Reservations\\ReservationController\\ReservationController::FindAll'], [], [['text', '/Reservations']], [], [], []],
    'getReservationById' => [['id'], ['_controller' => 'App\\Reservations\\ReservationController\\ReservationController::FindById'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Reservations']], [], [], []],
    'createReservation' => [[], ['_controller' => 'App\\Reservations\\ReservationController\\ReservationController::Create'], [], [['text', '/Reservations']], [], [], []],
    'updateReservation' => [['id'], ['_controller' => 'App\\Reservations\\ReservationController\\ReservationController::Update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Reservations']], [], [], []],
    'deleteReservation' => [['id'], ['_controller' => 'App\\Reservations\\ReservationController\\ReservationController::Delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/Reservations']], [], [], []],
    'restaurant_list' => [[], ['_controller' => 'App\\Restaurants\\RestaurantController\\RestaurantController::FindAll'], [], [['text', '/Restaurants']], [], [], []],
    'restaurant_authenticate' => [[], ['_controller' => 'App\\Restaurants\\RestaurantController\\RestaurantController::Authenticate'], [], [['text', '/Restaurants/authenticate']], [], [], []],
    'restaurant_show' => [['id'], ['_controller' => 'App\\Restaurants\\RestaurantController\\RestaurantController::FindById'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/Restaurants']], [], [], []],
    'restaurant_create' => [[], ['_controller' => 'App\\Restaurants\\RestaurantController\\RestaurantController::Create'], [], [['text', '/Restaurants']], [], [], []],
    'restaurant_update' => [['id'], ['_controller' => 'App\\Restaurants\\RestaurantController\\RestaurantController::Update'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/Restaurants']], [], [], []],
    'restaurant_delete' => [['id'], ['_controller' => 'App\\Restaurants\\RestaurantController\\RestaurantController::Delete'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/Restaurants']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
